### ISSUE TITLE
GTA 5 only white keys

### ISSUE THREAD

**Issue by Jimmbo6** [antonpup/Aurora#1015]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keys to follow Logitech's profile where keys follow player color and the police.

### Actual behavior:
When I load up GTA V with my Cosair K70 Lux RGB, all my keys just turn white and no more than that.

### How often does this problem occur?
Every time, Strangely enough Aurora worked perfectly before I reinstalled Windows,

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Download and install Aurora
2. Select Cosair K70 under devices.
3. Patch GTA V

### What is the version of Aurora you are experiencing this issue with?
I have tried latest stabile version and latest beta.

### Does the previous version of Aurora have this issue?
Yes.

### Please include any logs, screenshots, or files that are related to this issue:
=======================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 6
User DomainName: DESKTOP-DR77T0E
User Name: Jimmb
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[INFO] 07-03-2018 08:32:05: Program started with '-install_logitech' parameter
[INFO] 07-03-2018 08:32:05: Logitech LED SDK patched successfully
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 6
User DomainName: DESKTOP-DR77T0E
User Name: Jimmb
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[INFO] 07-03-2018 08:40:50: Program started with '-install_logitech' parameter
[INFO] 07-03-2018 08:40:50: Logitech LED SDK patched successfully

**Comment by simon-wh** [comment]
Could you try using [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases)?

**Comment by Jimmbo6** [comment]
Yes I just tried it. But no luck. Still wont change with the players.

**Comment by simon-wh** [comment]
Hm, not sure, I'll try and have a look into it in the next few days.

**Comment by Jimmbo6** [comment]
Thanks man. Appreciate it.

------ Original Meddelelse ------
Fra: "Simon W" <notifications@github.com>
Til: "antonpup/Aurora" <Aurora@noreply.github.com>
Cc: "Jimmbo6" <jimmbo6@gmail.com>; "Author" <author@noreply.github.com>
Sendt: 14-03-2018 23:31:10
Emne: Re: [antonpup/Aurora] GTA 5 only white keys (#1015)

**Comment by simon-wh** [comment]
Have you installed the wrapper required for GTA5 lighting to work? I've just tested it and don't have any issues.

**Comment by Jimmbo6** [comment]
Hey
Thanks for your help. I have tried both LightFX 64/32 and Logitech 
patch.

Can I uninstall all Aurora and try again, perhaps?

------ Original Meddelelse ------
Fra: "Simon W" <notifications@github.com>
Til: "antonpup/Aurora" <Aurora@noreply.github.com>
Cc: "Jimmbo6" <jimmbo6@gmail.com>; "Author" <author@noreply.github.com>
Sendt: 16-03-2018 22:19:29
Emne: Re: [antonpup/Aurora] GTA 5 only white keys (#1015)

**Comment by simon-wh** [comment]
Install the wrapper as per the instructions when you click "Show Profile Overview" when in the GTA 5 section

**Comment by Jimmbo6** [comment]
The instruktions only tells me to patch Logitech LED SDK. I have done 
that.

------ Original Meddelelse ------
Fra: "Simon W" <notifications@github.com>
Til: "antonpup/Aurora" <Aurora@noreply.github.com>
Cc: "Jimmbo6" <jimmbo6@gmail.com>; "Author" <author@noreply.github.com>
Sendt: 17-03-2018 11:12:40
Emne: Re: [antonpup/Aurora] GTA 5 only white keys (#1015)

**Comment by Jimmbo6** [comment]
If I close the program and try opening again I get this message.
Perhaps It's part of the problem.

------ Original Meddelelse ------
Fra: "Jimmi Meyer" <jimmbo6@gmail.com>
Til: "antonpup/Aurora" 
<reply@reply.github.com>
Sendt: 17-03-2018 15:18:15
Emne: Re[2]: [antonpup/Aurora] GTA 5 only white keys (#1015)

**Comment by simon-wh** [comment]
@Jimmbo6 What message? I don't see anything there.

**Comment by Jimmbo6** [comment]
The attached file I sent you. It was a screenshot of the message from Windows.

-
—
Jimmi Meyer

**Comment by simon-wh** [comment]
@Jimmbo6 There is no attachment

**Comment by Jimmbo6** [comment]
That is very strange. 




Sendt fra Mail til Windows 10

Fra: Simon W
Sendt: 20. marts 2018 00:22
Til: antonpup/Aurora
Cc: Jimmbo6; Mention
Emne: Re: [antonpup/Aurora] GTA 5 only white keys (#1015)

@Jimmbo6 There is no attachment

**Comment by simon-wh** [comment]
@Jimmbo6 I assume you attached something to the email you replied with? As that won't work on github, you either need to upload it somewhere else and link it or make a post on the website.

**Comment by Jimmbo6** [comment]
Ah that makes sence..

https://imgur.com/oFHFoag

This should work.

------ Original Meddelelse ------
Fra: "Simon W" <notifications@github.com>
Til: "antonpup/Aurora" <Aurora@noreply.github.com>
Cc: "Jimmbo6" <jimmbo6@gmail.com>; "Mention" 
<mention@noreply.github.com>
Sendt: 21-03-2018 14:27:44
Emne: Re: [antonpup/Aurora] GTA 5 only white keys (#1015)

**Comment by simon-wh** [comment]
That error requires you to delete %appdata%/Auora/Config.json. You should be running v0.6.1-dev4, because that issue appears when running v0.6.0b after dev4

**Comment by Jimmbo6** [comment]
Hey. Sorry for the late anwser.

But that did not do the trick.

But thanks for trying. I'm giving up on Aurora.

------ Original Meddelelse ------
Fra: "Simon W" <notifications@github.com>
Til: "antonpup/Aurora" <Aurora@noreply.github.com>
Cc: "Jimmbo6" <jimmbo6@gmail.com>; "Mention" 
<mention@noreply.github.com>
Sendt: 21-03-2018 21:05:30
Emne: Re: [antonpup/Aurora] GTA 5 only white keys (#1015)

**Comment by michaelsegreti95** [comment]
I'm having the same issue with GTA, my corsair keyboard goes all white(default menu). So aurora is detecting gta is running but it isn't getting the info on player state changes. I have tried applying the logitech patch, and even put the patch dll directly in the GTA folder but have had no success yet. Here is the log file from my most recent attempt if it's any help
[INFO] 03:50:59: Loading Configuration
[INFO] 03:51:00: Loading Plugins
[INFO] 03:51:00: Loading KB Layouts
[INFO] 03:51:00: Loading Input Hooking
[INFO] 03:51:01: Loading Applications
[INFO] 03:51:04: Loading Device Manager
[ERROR] 03:51:04: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 03:51:04: Device, Logitech, was not initialized
[INFO] 03:51:04: Corsair device, Initialized with x64-SDK
[INFO] 03:51:04: Device, Corsair, was initialized
[ERROR] 03:51:04: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 03:51:04: Device, Razer, was not initialized
[ERROR] 03:51:04: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 03:51:04: Device, Roccat, was not initialized
[ERROR] 03:51:05: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 03:51:05: Device, Clevo Keyboard, was not initialized
[INFO] 03:51:05: No Cooler Master devices successfully Initialized!
[INFO] 03:51:05: Device, Cooler Master, was not initialized
[INFO] 03:51:05: Device, AtmoOrb, was initialized
[ERROR] 03:51:05: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 03:51:05: Device, SteelSeries, was not initialized
[INFO] 03:51:05: No Wooting devices successfully Initialized!
[INFO] 03:51:05: Device, Wooting, was not initialized
[INFO] 03:51:05: Starting GameStateListener
[INFO] 03:51:05: Retrying Device Initialization
[ERROR] 03:51:05: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 03:51:05: Device, Logitech, was not initialized
[ERROR] 03:51:05: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 03:51:05: Device, Razer, was not initialized
[ERROR] 03:51:05: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 03:51:05: Device, Roccat, was not initialized
[ERROR] 03:51:05: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 03:51:05: Device, Clevo Keyboard, was not initialized
[INFO] 03:51:05: No Cooler Master devices successfully Initialized!
[INFO] 03:51:05: Device, Cooler Master, was not initialized
[ERROR] 03:51:05: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 03:51:05: Device, SteelSeries, was not initialized
[INFO] 03:51:05: Listening for game integration calls...
[INFO] 03:51:05: Loading ResourceDictionaries...
[INFO] 03:51:05: No Wooting devices successfully Initialized!
[INFO] 03:51:05: Device, Wooting, was not initialized
[INFO] 03:51:05: [IPCServer] Pipe created 49538252
[INFO] 03:51:05: [AuroraCommandsServerIPC] Pipe created 21647132
[INFO] 03:51:06: Loaded ResourceDictionaries
[INFO] 03:51:06: Loading ConfigUI...
[DEBUG] 03:51:07: Trying to get game path for: 232090
[INFO] 03:51:10: Retrying Device Initialization
[ERROR] 03:51:10: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 03:51:10: Device, Logitech, was not initialized
[ERROR] 03:51:10: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 03:51:10: Device, Razer, was not initialized
[ERROR] 03:51:10: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 03:51:10: Device, Roccat, was not initialized
[ERROR] 03:51:10: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 03:51:10: Device, Clevo Keyboard, was not initialized
[INFO] 03:51:10: No Cooler Master devices successfully Initialized!
[INFO] 03:51:10: Device, Cooler Master, was not initialized
[ERROR] 03:51:10: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 03:51:10: Device, SteelSeries, was not initialized
[INFO] 03:51:10: No Wooting devices successfully Initialized!
[INFO] 03:51:10: Device, Wooting, was not initialized
[INFO] 03:51:15: Retrying Device Initialization
[ERROR] 03:51:15: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 03:51:15: Device, Logitech, was not initialized
[ERROR] 03:51:15: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 03:51:15: Device, Razer, was not initialized
[ERROR] 03:51:15: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 03:51:15: Device, Roccat, was not initialized
[ERROR] 03:51:15: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 03:51:15: Device, Clevo Keyboard, was not initialized
[INFO] 03:51:15: No Cooler Master devices successfully Initialized!
[INFO] 03:51:15: Device, Cooler Master, was not initialized
[ERROR] 03:51:15: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 03:51:15: Device, SteelSeries, was not initialized
[INFO] 03:51:15: No Wooting devices successfully Initialized!
[INFO] 03:51:15: Device, Wooting, was not initialized
[INFO] 04:01:13: CaptureState is 
[INFO] 04:01:45: CaptureState is 
[INFO] 14:07:54: Logitech LED SDK patched successfully

**Comment by SahilRS200** [comment]
is there an update on this?
