### ISSUE TITLE
Background worker crash

### ISSUE THREAD

**Issue by mmmboost** [antonpup/Aurora#1046]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora shouldn't crash....?

### Actual behavior:
Upon resuming from sleep

### How often does this problem occur?
Seemingly every time I come back from a long pause

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Run aurora as usual
2. Lock workstation for a short time 
3. Unlock PC

(also happens on resume from sleep or screensaver)

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.1-dev4

### Does the previous version of Aurora have this issue?
I don't have this issue on my work PC with the same version.

### Please include any logs, screenshots, or files that are related to this issue:

Aurora fatally crashed. Please report the follow to author: 
System.InvaIidOperationException: This BackgroundWorker is currently 
busy and cannot run multiple tasks concurrently. 
System. ComponentModeI. BackgroundWorker RunWorkerAsync(Object 
argument) 
at Aurora. Devices. DeviceContainer. < ctor> sender, 
RunWorkerCompIetedEventArgs args) in 
er.cs:line 33 
System. ComponentModeI. BackgroundWorker .0nRunWorkerCompIete 
d(RunWorkerCompIetedEventArgs e) 
at System. Threading. Execution Context. RunlnternaI(ExecutionContext 
executionContext, ContextCaIIback callback* Object state, Boolean 
preserveSyncCtx) 
at System. Threa ding. ExecutionContext. Run (ExecutionContext 
executionContext, ContextCaIIback callback* Object state, Boolean 
preserveSyncCtx) 
System. Threading.QueueLlserWorkItemCaIIback. System. Threading. IThre 
adPooIWorkItem.ExecuteWorkItem0 
at System.Threading.ThreadPooIWorkQueue. Dispatch0

**Comment by NTripleOne** [comment]
I'm experiencing the same issue, background worker crashes - except it just seems to happen randomly.

I just turned my PC on and about 1 minute after logging in, aurora crashed with this error.

**Comment by brainbug89** [comment]
I got the same error. It's happening randomly and has nothing to do with sleep state of the PC.

**Comment by NTripleOne** [comment]
The weirdest part is, aurora seems to continue functioning perfectly fine after one of these crash dialogs pops up.

In fact, I have 3 of them open right now and everything's working fine, but clicking OK on any of them closes aurora.

https://i.imgur.com/v5xbQxp.png

I get the feeling this probably shouldn't be getting caught as a fatal error.

**Comment by brainbug89** [comment]
btw @mmmboost log is missing an important line. The error happens at line 33 in `Project-Aurora/Project-Aurora/Devices/DeviceManager.cs`

**Comment by mmmboost** [comment]
This is what I've come back to at my work PC after having been gone all weekend.  My computer was in sleep/hibernation most/all of the weekend as far as I can tell.


![2018-04-09_07-54-03](https://user-images.githubusercontent.com/34219833/38502001-865f82ba-3bcb-11e8-8ce6-fad1f36a5195.png)

**Comment by brainbug89** [comment]
@mmmboost I already posted a solution. So just wait until someone fixing it.

(btw I get such many error windows in just an hour) xD

**Comment by SnakePin** [comment]
Can you try and test edge build, it includes my commit https://ci.appveyor.com/project/antonpup/aurora/build/artifacts

**Comment by mmmboost** [comment]
Just downloaded and trying it now.  I'll keep you posted.

**Comment by NTripleOne** [comment]
Well, the 'crashes' are definitely rarer now, yesterday I didn't have any and today I only had one...

`[ERROR] 14:42:25: Fatal Exception caught : System.InvalidOperationException: This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.
   at System.ComponentModel.BackgroundWorker.RunWorkerAsync(Object argument)
   at Aurora.Devices.DeviceContainer.<.ctor>b__15_0(Object sender, RunWorkerCompletedEventArgs args) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\DeviceManager.cs:line 33
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[ERROR] 14:42:25: Runtime terminating: True
[INFO] 15:20:51: Show Window called`

**Comment by mmmboost** [comment]
@SnakePin Well it looks like your update has fixed my issue.  I tried this out on my work PC and I haven't had any crashed for the same reason since.  I'm going to give this a go on my home PC now.  I saw you made a pull-request.  How do we go about getting these changes to the master branch?  (sorry still a bit of a newb with git and open source)

**Comment by SnakePin** [comment]
@mmmboost They don't accept any commits to master branch but you can check my fork of the project. It has fixed master branch so changes are on the stable branch.
