### ISSUE TITLE
Every boot, AtmoOrb prevent SteelSeriesHID to start

### ISSUE THREAD

**Issue by Dubardo** [antonpup/Aurora#1365]
### Expected behavior:
SteelSeriesHID should start (I have a SteelSeries M800 APEX)

### Actual behavior:
AtmoOrb start even tho I don't have any

### How often does this problem occur?
Every boot. I have to manually stop AtmoOrb and manually start SteelSeries

### Please describe the steps to reproduce this issue:
Reboot 

### What is the version of Aurora you are experiencing this issue with?
Bet 0.6.3

### Does the previous version of Aurora have this issue?
No idea, where can I find these

### Please include any logs, screenshots, or files that are related to this issue:
[INFO] 16:19:23: 
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 8
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.6.3
========================================

[INFO] 16:19:23: Program started with '-silent' parameter
[INFO] 16:19:23: Loading Configuration
[INFO] 16:19:24: Loading Plugins
[INFO] 16:19:24: Loading KB Layouts
[INFO] 16:19:25: Loading Input Hooking
[INFO] 16:19:25: Loading Applications
[INFO] 16:19:27: Loading Device Manager
[ERROR] 16:19:27: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 16:19:27: Device, Logitech, was not initialized
[ERROR] 16:19:27: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16:19:27: Device, Corsair, was not initialized
[ERROR] 16:19:28: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 16:19:28: Device, Razer, was not initialized
[ERROR] 16:19:28: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 16:19:28: Device, Roccat, was not initialized
[ERROR] 16:19:28: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 16:19:28: Device, Clevo Keyboard, was not initialized
[INFO] 16:19:28: No Cooler Master devices successfully Initialized!
[INFO] 16:19:28: Device, Cooler Master, was not initialized
[INFO] 16:19:28: Device, AtmoOrb, was initialized
[ERROR] 16:19:30: SteelSeries GameSense SDK could not be initialized: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:56954
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at SteelSeries.GameSenseSDK.GameSenseSDK.sendPostRequest(String address, String payload) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 238
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 70
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 16:19:30: Device, SteelSeries, was not initialized
[INFO] 16:19:30: Device, SteelSeriesHID, was not initialized
[INFO] 16:19:30: No Wooting devices successfully Initialized!
[INFO] 16:19:30: Device, Wooting, was not initialized
[INFO] 16:19:30: Device, LightFX, was not initialized
[INFO] 16:19:30: Device, Sony DualShock 4(PS4), was not initialized
[INFO] 16:19:30: Starting GameStateListener
[INFO] 16:19:30: Retrying Device Initialization
[ERROR] 16:19:30: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 16:19:30: Device, Logitech, was not initialized
[ERROR] 16:19:30: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16:19:30: Device, Corsair, was not initialized
[ERROR] 16:19:30: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 16:19:30: Device, Razer, was not initialized
[ERROR] 16:19:30: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 16:19:30: Device, Roccat, was not initialized
[INFO] 16:19:30: Listening for game integration calls...
[INFO] 16:19:30: Loading ResourceDictionaries...
[ERROR] 16:19:30: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 16:19:30: Device, Clevo Keyboard, was not initialized
[INFO] 16:19:30: No Cooler Master devices successfully Initialized!
[INFO] 16:19:30: Device, Cooler Master, was not initialized
[INFO] 16:19:30: Loaded ResourceDictionaries
[INFO] 16:19:30: Loading ConfigUI...
[INFO] 16:19:30: [IPCServer] Pipe created 21647132
[INFO] 16:19:30: [AuroraCommandsServerIPC] Pipe created 6451435
[ERROR] 16:19:31: SteelSeries GameSense SDK could not be initialized: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:56954
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at SteelSeries.GameSenseSDK.GameSenseSDK.sendPostRequest(String address, String payload) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 238
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 70
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 16:19:31: Device, SteelSeries, was not initialized
[INFO] 16:19:31: Device, SteelSeriesHID, was not initialized
[INFO] 16:19:31: No Wooting devices successfully Initialized!
[INFO] 16:19:31: Device, Wooting, was not initialized
[INFO] 16:19:31: Device, LightFX, was not initialized
[INFO] 16:19:31: Device, Sony DualShock 4(PS4), was not initialized
[INFO] 16:19:36: Retrying Device Initialization
[ERROR] 16:19:36: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 16:19:36: Device, Logitech, was not initialized
[ERROR] 16:19:36: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16:19:36: Device, Corsair, was not initialized
[ERROR] 16:19:36: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 16:19:36: Device, Razer, was not initialized
[ERROR] 16:19:36: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 16:19:36: Device, Roccat, was not initialized
[ERROR] 16:19:36: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 16:19:36: Device, Clevo Keyboard, was not initialized
[INFO] 16:19:36: No Cooler Master devices successfully Initialized!
[INFO] 16:19:36: Device, Cooler Master, was not initialized
[ERROR] 16:19:37: SteelSeries GameSense SDK could not be initialized: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:56954
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at SteelSeries.GameSenseSDK.GameSenseSDK.sendPostRequest(String address, String payload) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 238
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 70
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 16:19:37: Device, SteelSeries, was not initialized
[INFO] 16:19:38: Device, SteelSeriesHID, was not initialized
[INFO] 16:19:38: No Wooting devices successfully Initialized!
[INFO] 16:19:38: Device, Wooting, was not initialized
[INFO] 16:19:38: Device, LightFX, was not initialized
[INFO] 16:19:38: Device, Sony DualShock 4(PS4), was not initialized
[INFO] 16:19:43: Retrying Device Initialization
[ERROR] 16:19:43: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 16:19:43: Device, Logitech, was not initialized
[ERROR] 16:19:43: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16:19:43: Device, Corsair, was not initialized
[ERROR] 16:19:43: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 16:19:43: Device, Razer, was not initialized
[ERROR] 16:19:43: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 16:19:43: Device, Roccat, was not initialized
[ERROR] 16:19:43: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 16:19:43: Device, Clevo Keyboard, was not initialized
[INFO] 16:19:43: No Cooler Master devices successfully Initialized!
[INFO] 16:19:43: Device, Cooler Master, was not initialized
[ERROR] 16:19:44: SteelSeries GameSense SDK could not be initialized: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:56954
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at SteelSeries.GameSenseSDK.GameSenseSDK.sendPostRequest(String address, String payload) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 238
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 70
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 16:19:44: Device, SteelSeries, was not initialized
[INFO] 16:19:44: Device, SteelSeriesHID, was not initialized
[INFO] 16:19:44: No Wooting devices successfully Initialized!
[INFO] 16:19:44: Device, Wooting, was not initialized
[INFO] 16:19:44: Device, LightFX, was not initialized
[INFO] 16:19:44: Device, Sony DualShock 4(PS4), was not initialized
[INFO] 16:23:05: Show Window called

**Comment by diogotr7** [comment]
You can disable AtmoOrb if you dont have one. Also, steelseriesHID only works for a couple of their mice. To use the keyboard, you should disable steelseriesHID and use the regular one.
