### ISSUE TITLE
Default (non-gaming) profile

### ISSUE THREAD

**Issue by Tiwas** [antonpup/Aurora#1378]
Hi guys,
Sorry for asking here, but I couldn't find anything useful in the wiki. Might be too tired, but as I couldn't sleep because of coughing (don't you love having a cold?) I needed something to do.

I would love to get some help setting up the following:
* when not in a game I'd like my keyboard to have some dim lighting, but once I start typing I'd like the keys to light up some. I was thinking breathing or something (that's when I hit a key and it will fill to all sides and then dim back down, right?). When the screen saver's active I'd like my keyboard to go dark.
* if possible, adjust the lighting by using some key sequence, like dim it if I game or work with the lights off

Is this possible? Could someone give me some pointers? Also, are there any current help documents out there?

Thanks!

**Comment by Tiwas** [comment]
For some reason it seems iCue has taken control of the lighting. Nothing I do in aurora makes any change to my keyboard and looking at lighting effects in iCue no longer says it's controlled by a third party app (like I think it usually says).  Is this a known problem with 0.6.3?

**Comment by diogotr7** [comment]
You can try checking aurora's device manager for the corsair integration. Also try restarting your system, that can help.

If it still doesnt help a log is helpful.

**Comment by Tiwas** [comment]
> You can try checking aurora's device manager for the corsair integration. Also try restarting your system, that can help.
> 
> If it still doesnt help a log is helpful.

For now, a reinstall was what was needed to get it going again. Where do I get the logs, if this happens again? Seems like the program tries to start, but hangs. I can see the process in task manager, but no icon appears in the task tray.

Also, is it possible to get a quick intro to the different layer types?

**Comment by Tiwas** [comment]
I decided to try 0.6.2 because 0.6.3 had too many issues. Below is my latest debug log.

```[INFO] 05:01:47: 
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: d:\Program Files\Aurora
Launch Directory: d:\Program Files\Aurora
Processor Count: 12
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.6.3
========================================

[ERROR] 05:01:47: An error occured while trying to load script d:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 40
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\DeviceManager.cs:line 129
[ERROR] 05:01:47: An error occured while trying to load script d:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 40
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\DeviceManager.cs:line 143
[INFO] 05:01:47: Loading Configuration
[INFO] 05:01:48: Loading Plugins
[INFO] 05:01:48: Loading KB Layouts
[INFO] 05:01:48: Loading Input Hooking
[INFO] 05:01:48: Loading Applications
[INFO] 05:01:49: Loading Device Manager
[ERROR] 05:01:49: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 05:01:49: Device, Logitech, was not initialized
[INFO] 05:01:49: Corsair device, Initialized with x64-SDK
[INFO] 05:01:49: Device, Corsair, was initialized
[ERROR] 05:01:49: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 05:01:49: Device, Razer, was not initialized
[ERROR] 05:01:49: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 05:01:49: Device, Roccat, was not initialized
[ERROR] 05:01:49: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 05:01:49: Device, Clevo Keyboard, was not initialized
[INFO] 05:01:50: No Cooler Master devices successfully Initialized!
[INFO] 05:01:50: Device, Cooler Master, was not initialized
[ERROR] 05:01:50: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 05:01:50: Device, SteelSeries, was not initialized
[INFO] 05:01:50: No Wooting devices successfully Initialized!
[INFO] 05:01:50: Device, Wooting, was not initialized
[INFO] 05:01:50: Device, LightFX, was not initialized
[INFO] 05:01:50: Starting GameStateListener
[INFO] 05:01:50: Retrying Device Initialization
[ERROR] 05:01:50: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 05:01:50: Device, Logitech, was not initialized
[ERROR] 05:01:50: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 05:01:50: Device, Razer, was not initialized
[ERROR] 05:01:50: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 05:01:50: Device, Roccat, was not initialized
[INFO] 05:01:50: Listening for game integration calls...
[INFO] 05:01:50: Loading ResourceDictionaries...
[ERROR] 05:01:50: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 05:01:50: Device, Clevo Keyboard, was not initialized
[INFO] 05:01:50: No Cooler Master devices successfully Initialized!
[INFO] 05:01:50: Device, Cooler Master, was not initialized
[ERROR] 05:01:50: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 05:01:50: Device, SteelSeries, was not initialized
[INFO] 05:01:50: [IPCServer] Pipe created 6451435
[INFO] 05:01:50: [AuroraCommandsServerIPC] Pipe created 34717384
[INFO] 05:01:50: No Wooting devices successfully Initialized!
[INFO] 05:01:50: Device, Wooting, was not initialized
[INFO] 05:01:50: Device, LightFX, was not initialized
[INFO] 05:01:50: Loaded ResourceDictionaries
[INFO] 05:01:50: Loading ConfigUI...
[INFO] 05:01:55: Retrying Device Initialization
[ERROR] 05:01:55: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 05:01:55: Device, Logitech, was not initialized
[ERROR] 05:01:55: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 05:01:55: Device, Razer, was not initialized
[ERROR] 05:01:55: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 05:01:55: Device, Roccat, was not initialized
[ERROR] 05:01:55: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 05:01:55: Device, Clevo Keyboard, was not initialized
[INFO] 05:01:55: No Cooler Master devices successfully Initialized!
[INFO] 05:01:55: Device, Cooler Master, was not initialized
[ERROR] 05:01:55: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 05:01:55: Device, SteelSeries, was not initialized
[INFO] 05:01:55: No Wooting devices successfully Initialized!
[INFO] 05:01:55: Device, Wooting, was not initialized
[INFO] 05:01:55: Device, LightFX, was not initialized
[INFO] 05:02:00: Retrying Device Initialization
[ERROR] 05:02:00: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 05:02:00: Device, Logitech, was not initialized
[ERROR] 05:02:00: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 05:02:00: Device, Razer, was not initialized
[ERROR] 05:02:00: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 05:02:00: Device, Roccat, was not initialized
[ERROR] 05:02:00: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 05:02:00: Device, Clevo Keyboard, was not initialized
[INFO] 05:02:00: No Cooler Master devices successfully Initialized!
[INFO] 05:02:00: Device, Cooler Master, was not initialized
[ERROR] 05:02:00: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 05:02:00: Device, SteelSeries, was not initialized
[INFO] 05:02:00: No Wooting devices successfully Initialized!
[INFO] 05:02:00: Device, Wooting, was not initialized
[INFO] 05:02:00: Device, LightFX, was not initialized
[INFO] 05:02:25: Show Window called
[ERROR] 18:44:46: Exception during Node parsing. Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Aurora.Profiles.Node`1..ctor(String json_data) in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\Node.cs:line 18
[ERROR] 18:51:55: Exception during Node parsing. Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Aurora.Profiles.Node`1..ctor(String json_data) in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\Node.cs:line 18
[INFO] 19:57:16: Show Window called
[INFO] 20:07:44: Device, Corsair, was shutdown
```

**Comment by diogotr7** [comment]
It sometimes hangs because it gets stuck when shutting down. If you close it manually in task manager it starts up again correctly,

**Comment by simon-wh** [comment]
@Tiwas Could you make a backup of %appdata%/Aurora and try v0.6.3 to help us try and debug this issue if you still get it? You can just download the zip and extract it to a folder so it doesn't overwrite your current version.
