### ISSUE TITLE
Cpu usage not showing when at desktop

### ISSUE THREAD

**Issue by bobaj0r** [antonpup/Aurora#138]
This error message is showing in the logs

[ERROR] 8/09/2016 4:10:57 PM: PerformanceCounter exception: System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.Initialize()
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at Aurora.Profiles.Desktop.Event_Desktop.getCPUCounter() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Desktop\Event_Desktop.cs:line 128

Not sure why it is not working as it was working previously.

Thanks.

**Comment by antonpup** [comment]
You have to rebuild the performance counters. To do so, you need to run this command two times either in cmd as admin on in run, `lodctr /R`

**Comment by bobaj0r** [comment]
Thanks! Had to do it under c:\windows\syswow64 but works now
