### ISSUE TITLE
Cannot run Aurora and MSI Afterburner at the same time.

### ISSUE THREAD

**Issue by Blizzardfall** [antonpup/Aurora#173]
Hello, recently I've found out I can't open Aurora while MSI Afterburner is running.
I can run both at the same time if I open Aurora first and MSI Afterburner later, but once I open Aurora(out of tray) my mouse cursor stops for a second and Aurora crashes.

I was using both at the same time before just fine, but I don't know what caused the problem.

My MSI Afterburner is v4.3.0.9130 Beta 14 and Aurora is 0.5.1c beta.
Maybe it's Windows problem, I'm in Windows 10 Insider Preview slow ring, currently build 14931.

**Comment by Blizzardfall** [comment]
And few little things I hope you can fix it:
G logo is supported, but I can't assign G910 logo. (http://i.imgur.com/0sqERla.png)
You can assign same keys on multiple color zones, I think it'd be nice to warn user when a key is assign on multiple color zones or remove older one automatically.

**Comment by antonpup** [comment]
I use MSI Afterburner and it's fine. Post your latest log, it will be in the "logs" folder.

I'll look into the assigning bug, thank you.

**Comment by Blizzardfall** [comment]
Here's the log.

========================================
Operation System: Windows 10 Pro Insider Preview
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: 컴퓨터
User Name: User
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

2016-10-09 오전 2:45:08: An error occured while trying to load script D:\Downloads\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in d:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 53
2016-10-09 오전 2:45:08: An error occured while trying to load script D:\Downloads\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in d:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 67
[INFO] 2016-10-09 오전 2:45:08: Device, Logitech, was initialized
[ERROR] 2016-10-09 오전 2:45:08: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2016-10-09 오전 2:45:08: Device, Corsair, was not initialized
[INFO] 2016-10-09 오전 2:45:08: No Chroma SDK available
[ERROR] 2016-10-09 오전 2:45:08: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 50
[INFO] 2016-10-09 오전 2:45:08: Device, Razer, was not initialized
[INFO] 2016-10-09 오전 2:45:08: Loading KB Layouts
[INFO] 2016-10-09 오전 2:45:08: Retrying Device Initialization
[ERROR] 2016-10-09 오전 2:45:08: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2016-10-09 오전 2:45:08: Device, Corsair, was not initialized
[INFO] 2016-10-09 오전 2:45:08: No Chroma SDK available
[ERROR] 2016-10-09 오전 2:45:08: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 50
[INFO] 2016-10-09 오전 2:45:08: Device, Razer, was not initialized
[INFO] Baseline X = 7
[INFO] Baseline Y = 0
[INFO] Baseline X = 44
[INFO] Baseline Y = 37
[INFO] 2016-10-09 오전 2:45:08: Input Hooking
[INFO] 2016-10-09 오전 2:45:08: Starting GameEventHandler
[INFO] 2016-10-09 오전 2:45:08: Starting GameStateListener
2016-10-09 오전 2:45:08: Listening for game integration calls...
2016-10-09 오전 2:45:08: Loading WinApp...
2016-10-09 오전 2:45:08: Loaded WinApp
2016-10-09 오전 2:45:08: Loading ResourceDictionaries...
2016-10-09 오전 2:45:08: [IPCServer] Pipe created 20974680
2016-10-09 오전 2:45:09: Loaded ResourceDictionaries
2016-10-09 오전 2:45:09: Loading ConfigUI...

**Comment by Blizzardfall** [comment]
I just added Aurora to RivaTuner Statistics Server so OSD is disabled on Aurora, and I can running both Afterburner and Aurora at the same time again.

Maybe my RTSS setting was the problem, so I'll just add it here.
![2016-10-09_16-24-36](https://cloud.githubusercontent.com/assets/19769002/19218751/fc661458-8e3c-11e6-8705-d51142ab28cf.jpg)
![2016-10-09_16-24-48](https://cloud.githubusercontent.com/assets/19769002/19218752/fc67819e-8e3c-11e6-8940-6643c18aca06.jpg)
