### ISSUE TITLE
ASUS Exception

### ISSUE THREAD

**Issue by mattgoode82** [antonpup/Aurora#1780]
I've got several ASUS RGB devices (STRIX 2080ti, Z390-I motherboard, RYUO cooler, G.SKILL RAM), however no devices are showing up for me; I'm just getting an exception - not sure whether I've failed to install a component somewhere along the way, or if this is a bona fide bug.

I installed using the windows executable installer - I don't have any other ASUS software on the system (couldn't see whether this is a requirement?)

```
[INFO] 18:35:45: 
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.7.0
========================================

[INFO] 18:35:45: Loading Configuration
[INFO] 18:35:46: Loading Plugins
[INFO] 18:35:46: Loading KB Layouts
[INFO] 18:35:46: Loading Input Hooking
[INFO] 18:35:46: Loading RazerManager
[WARN] 18:35:46: Currently installed razer sdk version "0.0.0" is not supported!
[INFO] 18:35:46: Loading Applications
[INFO] 18:35:48: Fetching latest pointers
[INFO] 18:35:48: Loading Device Manager
[ERROR] 18:35:48: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 18:35:48: Device, SteelSeries, was not initialized
[ERROR] 18:35:48: RGB.NET device (Asus), Exception! Message: Retrieving the COM class factory for component with CLSID {05921124-5057-483E-A037-E9497B523590} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
[INFO] 18:35:48: Device, Asus, was not initialized
[INFO] 18:35:48: Starting GameStateListener
[INFO] 18:35:48: Retrying Device Initialization
```

**Comment by diogotr7** [comment]
As far as I know you need Asus aura installed.
