### ISSUE TITLE
Unable to start Aurora following fresh install

### ISSUE THREAD

**Issue by mattchue** [antonpup/Aurora#1895]
### Expected Behaviour
Aurora should open when started.

### Actual Behaviour
Aurora does not open when started, crashing shortly after initialization.

### Reproduction steps
I believe this is an issue scoped to my local machine configuration, but - 
1) Installed Aurora having not previously installed it
2) Started Aurora
3) Observe Aurora crashing via Task Manager

### Frequency
Every time

### Aurora Version:
Stable, Latest, Bleeding Edge

### Previously an Issue?
First time I've attempted to use Aurora.

### Logs
(same output in this file on every startup attempt)
https://gist.github.com/mattchue/afad4ffc1c7cc5495d6a3cedfbcbf639

### Notes
- I have tried removing the AppData folder between installs.
- I have reviewed the logs and attempted to troubleshoot myself, but am unsure which error logged is fatal.
- I do see that Aurora's updater runs shortly before the app closes.

**Comment by diogotr7** [comment]
Quite a few more users are having this issue, so here are instructions to at least get aurora to start:

* Open the file Config.json located at %appdata%\Aurora.
* Find a line that says `"devices_disabled": {`
* Under `$values`, add `"Aurora.Devices.Asus.AsusDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"`. Make sure to add a comma to end of the previous line.
* Starting with the default configuration, it should look like this:

```  
"devices_disabled": {
    "$type": "System.Collections.Generic.HashSet`1[[System.Type, mscorlib]], System.Core",
    "$values": [
      "Aurora.Devices.Dualshock.DualshockDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.AtmoOrbDevice.AtmoOrbDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.NZXT.NZXTDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.Asus.AsusDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
    ]
  },
```
* Aurora Should start successfully now.

**Comment by diogotr7** [comment]
Using this issue for discussion.

I'm not sure what caused this issue to happen recently, o assume an update to asus aura. One option would be to disable asus support by default while we dont know what's happening exactly. If the affected users could post relevant Asus Aura hardware and the versions of asus aura / armoury or other relevant software, that helps a lot with trying to figure out what the issue is.

**Comment by LufyCZ** [comment]
> Quite a few more users are having this issue, so here are instructions to at least get aurora to start:
> 
> * Open the file Config.json located at %appdata%\Aurora.
> * Find a line that says `"devices_disabled": {`
> * Under `$values`, add `"Aurora.Devices.Asus.AsusDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"`. Make sure to add a comma to end of the previous line.
> * Starting with the default configuration, it should look like this:
> 
> ```
> "devices_disabled": {
>     "$type": "System.Collections.Generic.HashSet`1[[System.Type, mscorlib]], System.Core",
>     "$values": [
>       "Aurora.Devices.Dualshock.DualshockDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
>       "Aurora.Devices.AtmoOrbDevice.AtmoOrbDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
>       "Aurora.Devices.NZXT.NZXTDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
>       "Aurora.Devices.Asus.AsusDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
>     ]
>   },
> ```
> 
> * Aurora Should start successfully now.

Doesn't work for me. Attached the log.

[2020-01-28 21.13.00.log](https://github.com/antonpup/Aurora/files/4124366/2020-01-28.21.13.00.log)

**Comment by diogotr7** [comment]
Could you please look at event viewer and see if that has any more info? @LufyCZ

**Comment by LufyCZ** [comment]
> Could you please look at event viewer and see if that has any more info? @LufyCZ

Very little to no info:

![image](https://user-images.githubusercontent.com/20911347/73302793-8321d380-4215-11ea-9796-b8b5a5ec46f1.png)

![image](https://user-images.githubusercontent.com/20911347/73302815-8ddc6880-4215-11ea-99a2-3970689bc45a.png)

**Comment by xewl** [comment]
It worked before, with 7.2, but note that when I tried to set up Philips Hue, I needed to update to AURA. I tried this with both `Lighting_Control_1.07.71.zip` & `Lighting_Control_1.07.79`. (14/1/'20)
I'm not sure what version I had originally, though. But it was ~Sept'19
The only hardware I use it for is my motherboard, an `ASUS Maximus XI Formula`.
iCue did receive data for ~2sec and then Aurora crashed, as that hardware.

Your solution above, works for me.

>If the affected users could post relevant Asus Aura hardware and the versions of asus aura / armoury or other relevant software, that helps a lot with trying to figure out what the issue is.

**Comment by caiocabus** [comment]
Aurora doesn't work with Asus Mobo?

**Comment by xewl** [comment]
My Aurora bugged, I had to re-edit, and it added a line.
My `devices_disabled` inside `Config.json` now looks like this:

```
  "devices_disabled": {
    "$type": "System.Collections.Generic.HashSet`1[[System.Type, mscorlib]], System.Core",
    "$values": [
      "Aurora.Devices.Dualshock.DualshockDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.AtmoOrbDevice.AtmoOrbDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.NZXT.NZXTDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.UnifiedHID.UnifiedHIDDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.Asus.AsusDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
    ]
  },
```

**Comment by ShawnTheShadow** [comment]
Also getting the same thing once i installed Asus Aura 
`
Application: Aurora.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at AuraServiceLib.IAuraSdk2.Enumerate(UInt32)
   at RGB.NET.Devices.Asus.AsusDeviceProvider.Initialize(RGB.NET.Core.RGBDeviceType, Boolean, Boolean)
   at RGB.NET.Core.RGBSurface.LoadDevices(RGB.NET.Core.IRGBDeviceProvider, RGB.NET.Core.RGBDeviceType, Boolean, Boolean)
   at Aurora.Devices.RGBNet.AbstractRGBNetDevice.Initialize()
   at Aurora.Controls.Control_DeviceItem.btnToggleOnOff_Click(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Aurora.App.Main()`

**Comment by OHGODNO162534** [comment]
i dont know whats happening with mine but if i try to open i the first time, also after a fresh install it doesnt open, the second time itll give me an error, and itll say that its exitting the software, and it does the same thing when i try to open it again, dont know what happened, and also adding that code doesnt help

**Comment by BraVo75** [comment]
I have the same Problem like mattchue. The one thing I did was installing a WMR Headset. Before I had no problems.

The workaround with disabling Asus Service doesn't help. Here's my config:

`  "devices_disabled": {
    "$type": "System.Collections.Generic.HashSet`1[[System.Type, mscorlib]], System.Core",
    "$values": [
      "Aurora.Devices.Dualshock.DualshockDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.AtmoOrbDevice.AtmoOrbDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.NZXT.NZXTDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.UnifiedHID.UnifiedHIDDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Aurora.Devices.Asus.AsusDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
    ]
  },`

There are also no noteworthy log entries and the event log also says nothing bug "it crashed".

Any ideas?

**Comment by Timoms** [comment]
@BraVo75 Exactly the same issue, installed HP Reverb G2 with WMR / Mixed Reality Device and Aurora stopped working.

```Application: Aurora.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at SBAuroraReactive.LEDManager.EnumConnectedDevices()
   at Aurora.Devices.Creative.SoundBlasterXDevice.Initialize()
   at Aurora.Devices.DeviceManager.InitializeDevices()
   at Aurora.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Aurora.App.Main()

```
