### ISSUE TITLE
Volume Overlay stops working + crash

### ISSUE THREAD

**Issue by MysticBrightShadow** [antonpup/Aurora#2096]
### Expected Behaviour
Volume level overlay should be usable when needed.

### Actual Behaviour
After some amount of time the volume overlay stops working. At which point attempting to open Aurora from the taskbar causes a software crash, either silently without showing the application window, or the software window opens but is immediately not responsive and frozen. In process explorer I can see the software is using 6,769,188k bytes which seems to indicate a serious memory leak.

### Reproduction steps
Just use volume overlay and wait a while. Could be after a few hours.

### Frequency
Happens randomly but commonly.

### Aurora Version:
8.0

### Previously an Issue?
Did have a similar issue that happened when sleeping the computer on the last stable version (7.2?)

**Comment by diogotr7** [comment]
Do you have a log from when this happens?

**Comment by MysticBrightShadow** [comment]
[2020-06-13 13.04.12.log](https://github.com/antonpup/Aurora/files/4775757/2020-06-13.13.04.12.log)

**Comment by MysticBrightShadow** [comment]
I've just updated to 8.1. If I notice any difference I'll report it.

**Comment by MysticBrightShadow** [comment]
![aurora process](https://user-images.githubusercontent.com/66760856/84583029-b4f09c80-ada8-11ea-8d8b-127dd6481871.png)
This was with version 8.0 when the bug happened and the software froze as described above.

**Comment by MysticBrightShadow** [comment]
Happens with 8.1 as well.

**Comment by MysticBrightShadow** [comment]
[2020-06-13 19.01.33.log](https://github.com/antonpup/Aurora/files/4776179/2020-06-13.19.01.33.log)

**Comment by MysticBrightShadow** [comment]
[FATAL] 12:39:57: Fatal Exception caught : System.ComponentModel.Win32Exception (0x80004005): The current process has used all of its system allowance of handles for Window Manager objects
   at MS.Win32.UnsafeNativeMethods.CreateWindowEx(Int32 dwExStyle, String lpszClassName, String lpszWindowName, Int32 style, Int32 x, Int32 y, Int32 width, Int32 height, HandleRef hWndParent, HandleRef hMenu, HandleRef hInst, Object pvParam)
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   at System.Windows.Interop.HwndSource..ctor(HwndSourceParameters parameters)
   at System.Windows.Controls.Primitives.Popup.PopupSecurityHelper.BuildWindow(Int32 x, Int32 y, Visual placementTarget, Boolean transparent, HwndSourceHook hook, AutoResizedEventHandler handler, HwndDpiChangedEventHandler dpiChangedHandler)
   at System.Windows.Controls.Primitives.Popup.BuildWindow(Visual targetVisual)
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean asyncCall)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.OnDependencyPropertyChanged(DependencyObject d, DependencyProperty dp, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   at System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.OnToolTipChange(Boolean visible)
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.ProcessWindowMessage(UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.OnWindowMessageReceived(IntPtr hwnd, UInt32 messageId, IntPtr wparam, IntPtr lparam)
[FATAL] 12:39:57: Runtime terminating: True

**Comment by MysticBrightShadow** [comment]
[2020-06-14 01.58.04.log](https://github.com/antonpup/Aurora/files/4777086/2020-06-14.01.58.04.log)

**Comment by MysticBrightShadow** [comment]
"The current process has used all of its system allowance of handles for Window Manager objects" 

Seems the program is stuck in some sort of object creation loop.

**Comment by MysticBrightShadow** [comment]
I disabled all the modules (in device manager) I wasn't using (all of them except corsair) and that might have solved the issue. I'll report back in a few days.

**Comment by diogotr7** [comment]
This is definitely an issue with the devices being retried infinitely. Not sure what causes this but it's obviously an issue. I'll take a look when I have time.

**Comment by MysticBrightShadow** [comment]
So the issue still exists even though I turned off the other modules (which did reduce cpu usage of the software). It worked for longer then before, but it crashed with the same issue in the log after I noticed the volume overlay had stopped working. 
[2020-06-15 23.01.30.log](https://github.com/antonpup/Aurora/files/4788790/2020-06-15.23.01.30.log)

**Comment by GIGAkunX** [comment]
Hey everyone. Hate to bump this but I'm also experiencing this issue.
Fatal Exception caught : System.ComponentModel.Win32Exception (0x80004005)
However I'm not using the volume overlay. Any update on this?
[2020-10-01 06.16.24.log](https://github.com/antonpup/Aurora/files/5315179/2020-10-01.06.16.24.log)
