### ISSUE TITLE
randomly stopped recognising keyboard and mouse

### ISSUE THREAD

**Issue by werdna87** [antonpup/Aurora#220]
Recently, and seemingly randomly, everything just stopped working. whenever i try to start Aurora, the log says:

`11/22/2016 2:47:53 AM: An error occured while trying to load script C:\Users\aborg\Downloads\release_major_0_5_1d (1)\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in d:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 53
11/22/2016 2:47:53 AM: An error occured while trying to load script C:\Users\aborg\Downloads\release_major_0_5_1d (1)\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in d:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 67
[INFO] 11/22/2016 2:47:55 AM: Device, Logitech, was initialized`

I am using a g910 and a g900 that used to both work perfectly

**Comment by antonpup** [comment]
I am not sure... those errors in the log are perfectly normal.

**Comment by werdna87** [comment]
It's as if it doesn't detect the keyboard. It doesn't show up at all

**Comment by antonpup** [comment]
Did you do anything like update LGS? Make sure that the "Enable SDK" is enabled in LGS settings. Have you tried reinstalling LGS?

**Comment by werdna87** [comment]
I'm actually about to head away for a week for Thanksgiving, I can play
with it when I get back. The only thing I can think of is that I updated my
mouse firmware... Can't imagine that would break it though. I'll try
reinstalling LGS first

**Comment by antonpup** [comment]
Any updates on this?
