### ISSUE TITLE
razer chroma support disabled 

### ISSUE THREAD

**Issue by sleet437** [antonpup/Aurora#2284]
unfortunately razer has updated their razer chroma sdk and now its disabled on aurora.  can someone help with this?

![Screenshot (23)](https://user-images.githubusercontent.com/80075251/110062306-0118ae00-7d37-11eb-9e29-09c60cdf04be.png)

this is on every update from v0.8.1 to v0.8.1 +901

**Comment by AestheticsKSK** [comment]
Hi sleet, I had the same problem I reinstalled Razer completely, the option "repair or uninstall and reinstall" did not work so I uninstalled it and downloaded the installer on razers site. After you have uninstalled Razer Synapse and stuff you go into Aurora and uninstall the "Supported Version" you may have to restart afterwards but after a few tries I got mine to look like installed version "1.0" now install Razer and wait till it asks you to restart again. Mine looks like the attached image and works again :) 

P.s I noticed you're using the Blackwidow aswell does your spacebar and your media keys work? 
![Screenshot_Razer](https://user-images.githubusercontent.com/80130634/110214129-7b664100-7ea3-11eb-8bc8-db5c8b9d6a4a.png)

**Comment by sleet437** [comment]
you said uninstall the supported version. which version of aurora are you running?

**Comment by sleet437** [comment]
and no those keys do not

**Comment by AestheticsKSK** [comment]
Hi again, I am using the latest version of aurora the beta 0.8.1.

**Comment by milovincent** [comment]
> Hi sleet, I had the same problem I reinstalled Razer completely, the option "repair or uninstall and reinstall" did not work so I uninstalled it and downloaded the installer on razers site. After you have uninstalled Razer Synapse and stuff you go into Aurora and uninstall the "Supported Version" you may have to restart afterwards but after a few tries I got mine to look like installed version "1.0" now install Razer and wait till it asks you to restart again. Mine looks like the attached image and works again :)
> 
> P.s I noticed you're using the Blackwidow aswell does your spacebar and your media keys work?
> ![Screenshot_Razer](https://user-images.githubusercontent.com/80130634/110214129-7b664100-7ea3-11eb-8bc8-db5c8b9d6a4a.png)

what exactly did you do? after uninstalling synapse, pressing the uninstall button in the screenshot immediately gives me a dialogue telling me to reboot (which i have tried doing 6 times), after which nothing happens. how long did it take?

**Comment by gollenia** [comment]
I'm having the same issuie suddenly. I reinstalled Synapse completely, Aurora aswell, I uninstalled and reinstalled the  Supported version, nothing. It still says disabled. In the Chroma Studio, no App is listed (Aurora was listed formerly)

**Comment by gollenia** [comment]
In the logs, i found the following Error Message:
[ERROR] 19:29:50: Razer device, Exception! Message:System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei System.Object.GetType()
   bei Corale.Colore.Core.RegistryHelper.IsSdkAvailable()
   bei Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:Zeile 60.

(Sorry, it's in german, but it seems, as if the connection to possible)

**Comment by muckelba** [comment]
Same here. Just started with Aurora today and installed Razer Synapse, but all i've got is: 
![image](https://user-images.githubusercontent.com/34460584/113348029-5fd14780-9336-11eb-9eb5-b64a8779a413.png)

And the exact same errormessage as gollenia.

Let me know if i can help debugging this problem

**Comment by Zacaum** [comment]
Same problem here
![meh](https://user-images.githubusercontent.com/81997806/113627642-31a37e80-963a-11eb-820a-451fa6b54b3f.PNG)

**Comment by Jay2645** [comment]
Also having this same issue.

**Comment by Jay2645** [comment]
I'm also having this same issue; it may be related to #2180.

[Here are my logs.](https://github.com/antonpup/Aurora/files/6388507/2021-04-27.18.30.48.log)

I've uninstalled/reinstalled Synapse a number of times; I've tried installing Chroma through the Razer installer and patching afterwards as well as installing Synapse without Chroma and trying to patch it through Aurora. I've also tried patching the System32 .dlls (`RzChromaSDK.dll` and `RzChromaSDK64.dll`) as well as the respective .dlls in Program Files/Program Files (x86).

These log lines seem suspect in the main Aurora logs:
```
[ERROR] 18:31:24: Razer device, Exception! Message:System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Corale.Colore.Core.RegistryHelper.IsSdkAvailable()
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 60
```

I can also see that an `Aurora.exe.log` was created in `C:\Program Files (x86)\Razer Chroma SDK\logs`: [Aurora.exe.log](https://github.com/antonpup/Aurora/files/6388533/Aurora.exe.log) 

This log correctly detects when Aurora is open/closed. The entire time, though, Aurora is reporting that it can't connect, and it wasn't showing up on Synapse.

![image](https://user-images.githubusercontent.com/2058763/116333802-fdc6ff00-a788-11eb-80e2-927db021a3af.png)

**Comment by TheBob12** [comment]
Having the same issue here...

**Comment by TheRealBrownie** [comment]
Same Problem here, still no Solution?

**Comment by DarkyShadoW** [comment]
I'm new on razer, so I suppoused this should be plug and play like Logitech, but it seems still not working with Razer Synapse

**Comment by Gulugumi** [comment]
I have the same issue. No solution? I have attached a log, if it help
[2021-10-21 19.33.52.log](https://github.com/antonpup/Aurora/files/7391888/2021-10-21.19.33.52.log)
s.

**Comment by Masamune3210** [comment]
There is also a lovely bug where some interaction between Aurora and the Chroma SDK causes it to get stuck at 100% CPU usage

**Comment by adamnesh** [comment]
Same issue here, I tried reinstalling razer synapse multitude of times (uninstall, reinstall), the Razer SDK service is running in task manager, error log shows it loaded razer sdk:
[INFO] 14:49:16: RazerSdkManager loaded successfully!

but then the same error occurs to me:
[ERROR] 14:49:19: Razer device, Exception! Message:System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Corale.Colore.Core.RegistryHelper.IsSdkAvailable()
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 60
[INFO] 14:49:19: Device, Razer, was not initialized

please help

**Comment by garzy** [comment]
It seems that this project is no longer being maintained, the last update was on Jun 13, 2020. RIP Aurora. Uninstalling in 3,2,1 ....
