### ISSUE TITLE
Aurora fatally crashed - EvaluateRegistry -> FileNotFoundException

### ISSUE THREAD

**Issue by Jawfin** [antonpup/Aurora#2347]
Screenshot of crash report.
![image](https://user-images.githubusercontent.com/4596849/132157223-e6cf23f7-831a-4d5a-b057-bec54703a5bb.png)

Log (which doesn't seem to contain the error) : -

> [INFO] 13:21:14: Retrying Device Initialization
> [ERROR] 13:21:14: Logitech LED SDK could not be initialized.
> [INFO] 13:21:14: Device, Logitech, was not initialized
> [ERROR] 13:21:14: Razer device, Exception! Message:System.Exception: No Chroma SDK available
>    at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 67
> [INFO] 13:21:14: Device, Razer, was not initialized
> [ERROR] 13:21:14: Roccat device, Exception! Message:System.Exception: No devices connected
>    at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
> [INFO] 13:21:14: Device, Roccat, was not initialized
> [ERROR] 13:21:14: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
>    at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
> [INFO] 13:21:14: Device, Clevo Keyboard, was not initialized
> [INFO] 13:21:14: No Cooler Master devices successfully Initialized!
> [INFO] 13:21:14: Device, Cooler Master, was not initialized
> [ERROR] 13:21:14: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
>    at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
>    at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
> [INFO] 13:21:14: Device, SteelSeries, was not initialized
> [INFO] 13:21:14: No Wooting devices successfully Initialized!
> [INFO] 13:21:14: Device, Wooting, was not initialized
> [INFO] 13:21:14: Device, SoundBlasterX, was not initialized
> [INFO] 13:21:14: Device, LightFX, was not initialized
> [ERROR] 13:21:14: Drevo Radi SDK could not be initialized.
> [INFO] 13:21:14: Device, Drevo, was not initialized
> [ERROR] 13:21:14: Device YeeLight encountered an error while connecting. Exception: System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 0.0.0.0:55443
>    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
>    at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
>    at Aurora.Devices.YeeLight.YeeLightDevice.Connect(IPAddress lightIP, DoWorkEventArgs token) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\YeeLight\YeeLightDevice.cs:line 157
>    at Aurora.Devices.YeeLight.YeeLightDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\YeeLight\YeeLightDevice.cs:line 48
> [INFO] 13:21:14: Device, YeeLight, was not initialized
> [INFO] 13:21:14: [ASUS] Could not find Asus Aura SDK, please install version v1.07.71
> [INFO] 13:21:14: Device, Asus, was not initialized
> [INFO] 13:21:14: Vulcan device not initialized
> [INFO] 13:21:14: Device, Vulcan, was not initialized
> [INFO] 13:21:14: Device, Uniwill, was not initialized
> [INFO] 13:21:14: Device, Ducky, was not initialized
> 

### Expected Behaviour
Not crashing fatally.

### Actual Behaviour
Crashing fatally.

### Reproduction steps
Running Aurora.
Interestingly if I leave that crash window open Aurora is still running - I just can't get to the GUI.
If I need to change something I need to uninstall / reinstall, and it runs the first time, allowing me to change - from then on it crashes. 

### Frequency
Every time.  I run Aurora automatically on start-up = crash. Running again from the start menu  = crash. Running the exe from explorer = crash.

### Aurora Version:
Can't run, where is version number?  Aurora.exe file version is 0.8.1.0

### Previously an Issue?
Don't know.

Suggestion would be to change that error dialog so the text is selectable for copy/paste.
The error box is so large I can't see the bottom of it - so if there is a Copy Text button there I cannot see or access it.  (I just checked with Alt+Space M Up arrow to move it off the top of the window - no Copy Text button.)

It may be relevant that Aurora is not installed in the _Program Files_ folder - but I have run it for a year without problem from where it currently resides.

**Comment by Jawfin** [comment]
Update: log now has: -

> [INFO] 13:33:14: Loading ConfigUI...
> [FATAL] 13:33:15: Fatal Exception caught : System.TypeInitializationException: The type initializer for 'Aurora.Settings.Overrides.Logic.EvaluatableRegistry' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.EnterpriseServices.Wrapper.dll' or one of its dependencies. The specified module could not be found.
> 

I'll check see if my antivirus has eaten any files from there - MalwareBytes Pro & Windows Defender.
My keyboard is a Corsair.

**Comment by ghost** [comment]
This was fixed https://github.com/antonpup/Aurora/commit/a2267123080ba9dc31aa4c44210f0f920871662b

**Comment by Jawfin** [comment]
Thank you for that. How do I get the build with the fix? Would it be the most recent release, bleeding-edge, or download the source and compile it myself? Are there nightlies - would they help?

**Comment by ghost** [comment]
> 
> 
> Thank you for that. How do I get the build with the fix? Would it be the most recent release, bleeding-edge, or download the source and compile it myself? Are there nightlies - would they help?

You can compile the latest dev branch and should be fine
