### ISSUE TITLE
Razer Ornata not working

### ISSUE THREAD

**Issue by JoshDun66** [antonpup/Aurora#2368]
Hey, 
i just bought Razer Ornata keyboard today and i went str8 up to Aurora webpage to download the software (and razer synapse one aswell). I installed it and open up a dying light from my steam account. I got no effects in game. Upon further inspection i noticed that in Aurora device manager Razer is listed as "not initialized".. I was looking for help in Aurora discord where i got a beta build link... i tried beta version and it still doesnt work... Any help?

### Expected Behaviour
Starting up Aurora, connecting keyboard, opening game and having the effects work 

### Actual Behaviour
No effects in games

### Reproduction steps
starting up Aurora

### Frequency
Everytime

### Aurora Version:
beta v0.8.1 +173

### Previously an Issue?
New user

[2021-12-29 20.35.21.log](https://github.com/antonpup/Aurora/files/7790509/2021-12-29.20.35.21.log)

**Comment by hugoalves6** [comment]
I can't add anything to my chroma ornata either, even simple lightning and syncing with razer studio is impossible, it says it is installed but on trying to start it it does nothing
![20220219233536743](https://user-images.githubusercontent.com/4621600/154822654-5c2dfd28-dafd-4e72-a558-2fa9c193f9a5.png)

![20220219233639851](https://user-images.githubusercontent.com/4621600/154822661-1e407c16-0b4b-4ead-9f63-afb02fc538c5.png)

Even after trying to force start, refreshing, disable and enable again, refreshing, but still nothing.

**Comment by keiichi000** [comment]
I see a similiar issue.  The Chroma App installation apparently stops working on Chroma SDK version 3.25.01 and shows what @hugoalves6 has captured in their screen cap.  If you uninstall and reinstall Aurora, it simply can't initialize the Chroma SDK session (And in some instances, causes the Chroma SDK server to lock up).  It appears that Aurora can detect it and do the basic connection to it, but it can't initialize a session and start the Chroma App.  When I look at the logs, I see this error every time I try to get it to connect to Chroma

[ERROR] 20:45:52: Razer device, Exception! Message:System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Corale.Colore.Core.RegistryHelper.IsSdkAvailable()
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 60

**Comment by JaceMasters** [comment]
Little late to the party, but I have a similar issue here, as well. The Chroma app isn't initializing and isn't listed in Synapse either.

I am getting the same message as @keiichi000 in my logs: 
[ERROR] 09:16:13: Razer device, Exception! Message:System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Corale.Colore.Core.RegistryHelper.IsSdkAvailable()
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 60

Coincidentally, no "C:\projects" folder exists on my PC, so there might be something in that.

**Comment by Ashgar225** [comment]
Same story here, on a Huntsman TKL on Windows 10. I likewise do not have the mentioned project folder. I had Aurora working on my previous keyboard, which was a Logitech G813. Aurora detects Synapse version 3.27.3 but is "Disabled", and I get the above-referenced error if I try to hit the "Start" button in Device Manager.

![image](https://user-images.githubusercontent.com/1242954/180586066-80bb961b-17f5-42a7-8db6-7cfb6f542f62.png)

**Comment by Aytackydln** [comment]
This repository is no longer maintained. Get the more modern version here:
https://github.com/Aurora-RGB/Aurora

Also the screenshot is "Chroma Grabber". It is related to getting keyboard data provided by games and the top "Disabled" is mostly fine.
