### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by Shastarocks** [antonpup/Aurora#449]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Not launching)

### Expected behavior:
Explain here what should happen.
To launch...
### Actual behavior:
Explain here what happened instead.
I instlled aurora correctly but the app wont launch.
### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. attempting to Launching aroura
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (just got it), did/did not have this issue.

**Comment by antonpup** [comment]
Can you try running Aurora as admin? If it still does not launch, please attach a log it produces in the install directory/logs folder.

**Comment by Shastarocks** [comment]
2/12/2017 5:09:52 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 57
2/12/2017 5:09:52 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 71
[INFO] 2/12/2017 5:09:52 PM: Loading Configuration
[INFO] Profiles directory for Battlefield 3 does not exist.
[INFO] Profiles directory for Blacklight: Retribution does not exist.
[INFO] Profiles directory for Magic: The Gathering - Duels of the Planeswalkers 2012 does not exist.
[INFO] Profiles directory for Middle-earth: Shadow of Mordor does not exist.
[INFO] Profiles directory for Serious Sam 3 does not exist.
[INFO] Profiles directory for Robot Roller-Derby Disco Dodgeball does not exist.
[INFO] Profiles directory for XCOM: Enemy Unknown does not exist.
[INFO] Profiles directory for Evolve Stage 2 does not exist.
[INFO] Profiles directory for Metro: Last Light does not exist.
[INFO] Profiles directory for Guild Wars 2 does not exist.
[INFO] Profiles directory for Worms W.M.D does not exist.
[INFO] Profiles directory for Blade and Soul does not exist.
[INFO] Profiles directory for Battlefield 3 does not exist.
[INFO] Profiles directory for Blacklight: Retribution does not exist.
[INFO] Profiles directory for Magic: The Gathering - Duels of the Planeswalkers 2012 does not exist.
[INFO] Profiles directory for Middle-earth: Shadow of Mordor does not exist.
[INFO] Profiles directory for Serious Sam 3 does not exist.
[INFO] Profiles directory for Robot Roller-Derby Disco Dodgeball does not exist.
[INFO] Profiles directory for XCOM: Enemy Unknown does not exist.
[INFO] Profiles directory for Evolve Stage 2 does not exist.
[INFO] Profiles directory for Metro: Last Light does not exist.
[INFO] Profiles directory for Guild Wars 2 does not exist.
[INFO] Profiles directory for Worms W.M.D does not exist.
[INFO] Profiles directory for Blade and Soul does not exist.
[INFO] 2/12/2017 5:09:54 PM: Loading Device Manager
[INFO] 2/12/2017 5:09:54 PM: Device, Logitech, was initialized
[ERROR] 2/12/2017 5:09:54 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/12/2017 5:09:54 PM: Device, Corsair, was not initialized
[INFO] 2/12/2017 5:09:54 PM: No Chroma SDK available
[ERROR] 2/12/2017 5:09:54 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/12/2017 5:09:54 PM: Device, Razer, was not initialized
[INFO] 2/12/2017 5:09:54 PM: Could not connect to Clevo WMI Interface
[ERROR] 2/12/2017 5:09:54 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 2/12/2017 5:09:54 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 2/12/2017 5:09:54 PM: Cooler Master device control could not be initialized
[INFO] 2/12/2017 5:09:54 PM: Device, Cooler Master, was not initialized
[INFO] 2/12/2017 5:09:54 PM: Device, AtmoOrb, was initialized
[INFO] 2/12/2017 5:09:54 PM: Loading KB Layouts
[INFO] 2/12/2017 5:09:54 PM: Retrying Device Initialization
[ERROR] 2/12/2017 5:09:54 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/12/2017 5:09:54 PM: Device, Corsair, was not initialized
[INFO] 2/12/2017 5:09:54 PM: No Chroma SDK available
[ERROR] 2/12/2017 5:09:54 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/12/2017 5:09:54 PM: Device, Razer, was not initialized
[INFO] 2/12/2017 5:09:54 PM: Could not connect to Clevo WMI Interface
[ERROR] 2/12/2017 5:09:54 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 2/12/2017 5:09:54 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 2/12/2017 5:09:54 PM: Cooler Master device control could not be initialized
[INFO] 2/12/2017 5:09:54 PM: Device, Cooler Master, was not initialized
[INFO] Baseline X = 0
[INFO] Baseline Y = 0
[INFO] 2/12/2017 5:09:54 PM: Input Hooking
[INFO] 2/12/2017 5:09:54 PM: Starting GameEventHandler
[INFO] 2/12/2017 5:09:54 PM: Starting GameStateListener

**Comment by Shastarocks** [comment]
tried running as admin multiple times

**Comment by antonpup** [comment]
That's not the entire log. Can you please upload the entire log file to [http://pastebin.com/](http://pastebin.com/)?

Does it give any error messages?

**Comment by Shastarocks** [comment]
http://pastebin.com/gHWqiG3V

there is the pastebin link

**Comment by Shastarocks** [comment]
it didnt give any error messages that i know of

**Comment by antonpup** [comment]
Could you please run these two commands as admin in command prompt:
```
netsh http add urlacl url=http://localhost:9088/ user=Everyone listen=yes
netsh http add urlacl url=http://127.0.0.1:9088/ user=Everyone listen=yes
```

It's also possible that your anti-virus is blocking Aurora.

**Comment by Shastarocks** [comment]
the log at the beginigh says
`2/12/2017 6:39:30 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32`

**Comment by antonpup** [comment]
I can see, but it is unrelated to your problem.

**Comment by Shastarocks** [comment]
after inputing that code, it still doesnt work tho, even as admin. The code said it was added.

**Comment by Shastarocks** [comment]
is there anything you or i can do?

**Comment by antonpup** [comment]
I am not sure why it crashes without any error. Does the Aurora process stick around in Task Manager?

**Comment by Shastarocks** [comment]
no it does not.

**Comment by Shastarocks** [comment]
when i double click it, it doesn't even do anything even as administrator.

**Comment by Shastarocks** [comment]
i ran the trouble shooter from windows and it said incompatible version.

**Comment by Shastarocks** [comment]
wait is the program avalible for windows 10?

**Comment by Shastarocks** [comment]
i really wish i could us this program, it looks like so much fun based on what ive seen.

**Comment by Shastarocks** [comment]
is this my problem?

> [2F38:478C][2017-02-14T21:14:22]i001: Burn v3.7.3813.0, Windows v10.0 (Build 14393: Service Pack 0), path: C:\Users\Melton\AppData\Local\Temp\is-PPJPC.tmp\vcredist_x64.exe, cmdline: '-burn.unelevated BurnPipe.{138E13C0-4016-437E-B628-967F8B466CD6} {F171A6BB-9378-4B4B-9DC5-3EF579EDAA84} 15616'
[2F38:478C][2017-02-14T21:14:22]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\Melton\AppData\Local\Temp\dd_vcredist_amd64_20170214211422.log'
[2F38:478C][2017-02-14T21:14:22]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\Melton\AppData\Local\Temp\is-PPJPC.tmp\vcredist_x64.exe'
[2F38:478C][2017-02-14T21:14:22]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\Users\Melton\AppData\Local\Temp\is-PPJPC.tmp\'
[2F38:478C][2017-02-14T21:14:23]i000: Setting string variable 'WixBundleName' to value 'Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.23026'
[2F38:478C][2017-02-14T21:14:23]i100: Detect begin, 10 packages
[2F38:478C][2017-02-14T21:14:23]i000: Setting version variable 'windows_uCRT_DetectKey' to value '10.0.10240.16390'
[2F38:478C][2017-02-14T21:14:23]i000: Setting numeric variable 'windows_uCRT_DetectKeyExists' to value 1
[2F38:478C][2017-02-14T21:14:23]i102: Detected related bundle: {d992c12e-cab2-426f-bde3-fb8c53950b0d}, type: Upgrade, scope: PerMachine, version: 14.0.24215.1, operation: Downgrade
[2F38:478C][2017-02-14T21:14:23]i108: Detected compatible package: vcRuntimeMinimum_x64, provider: Microsoft.VS.VC_RuntimeMinimumVSU_amd64,v14, installed: {50A2BC33-C9CD-3BF1-A8FF-53C10A0B183C}, version: 14.0.24215, chained: {0D3E9E15-DE7A-300B-96F1-B4AF12B96488}
[2F38:478C][2017-02-14T21:14:23]i103: Detected related package: {50A2BC33-C9CD-3BF1-A8FF-53C10A0B183C}, scope: PerMachine, version: 14.0.24215.0, language: 0 operation: Downgrade
[2F38:478C][2017-02-14T21:14:23]i108: Detected compatible package: vcRuntimeAdditional_x64, provider: Microsoft.VS.VC_RuntimeAdditionalVSU_amd64,v14, installed: {EF1EC6A9-17DE-3DA9-B040-686A1E8A8B04}, version: 14.0.24215, chained: {BC958BD2-5DAC-3862-BB1A-C1BE0790438D}
[2F38:478C][2017-02-14T21:14:23]i103: Detected related package: {EF1EC6A9-17DE-3DA9-B040-686A1E8A8B04}, scope: PerMachine, version: 14.0.24215.0, language: 0 operation: Downgrade
[2F38:478C][2017-02-14T21:14:23]i052: Condition '(windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10137.0)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i052: Condition '(windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10137.0)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i052: Condition '(windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10137.0)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i052: Condition '(windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10137.0)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i052: Condition '(windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10137.0)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i052: Condition '(windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10137.0)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i052: Condition '(windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10137.0)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i052: Condition '(windows_uCRT_DetectKeyExists AND windows_uCRT_DetectKey >= v10.0.10137.0)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: vcRuntimeMinimum_x64, state: Obsolete, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: vcRuntimeAdditional_x64, state: Obsolete, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: Windows81_x86, state: Present, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: Windows81_x64, state: Present, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: Windows8_x86, state: Present, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: Windows8_x64, state: Present, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: Windows7_MSU_x86, state: Present, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: Windows7_MSU_x64, state: Present, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: WindowsVista_MSU_x86, state: Present, cached: None
[2F38:478C][2017-02-14T21:14:23]i101: Detected package: WindowsVista_MSU_x64, state: Present, cached: None
[2F38:478C][2017-02-14T21:14:23]i052: Condition 'VersionNT64 >= v6.0 OR (VersionNT64 = v5.2 AND ServicePackLevel >= 1)' evaluates to true.
[2F38:478C][2017-02-14T21:14:23]i199: Detect complete, result: 0x0
[2F38:1448][2017-02-14T21:14:29]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

after i run the installer, it says this to install visual bacic.

**Comment by antonpup** [comment]
Your issue is related to networking crashing on startup.

I may have found the cause of the issue. I'll let you know if I need you to test anything.

**Comment by Shastarocks** [comment]
ok thanks.

**Comment by Shastarocks** [comment]
ok, i reinstalled it and when i double click it, the top 3 rows of my keys will flash, then it wont open.

**Comment by Shastarocks** [comment]
i also updated the lgs and firmware on the keyboard too.

**Comment by Shastarocks** [comment]
it works fine on m laptop but the laptop is not even close to as good as my desktop.

**Comment by Shastarocks** [comment]
how do i get the version with the fix? or are you still working on it?

**Comment by Shastarocks** [comment]
let me know if there is anything i can do. i really want to play with this program.

**Comment by Shastarocks** [comment]
it still doesnt work

**Comment by antonpup** [comment]
I know. Because I haven't worked on Aurora in favor of doing other things. There's no need to keep this updated as if it is your Facebook feed. When it's fixed, it will be mentioned here.

**Comment by Shastarocks** [comment]
for some reason it is working now, i think it was a program caled lavasoft adware.
