### ISSUE TITLE
Literally Not Launching.

### ISSUE THREAD

**Issue by Sharpie3421** [antonpup/Aurora#486]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
it should open.
### Actual behavior:
Explain here what happened instead.
It didn't open, instead it says "Would you like to put the files in the archive" after attempting a launch. (I've tried launching as administator)
### How often does this problem occur?

This problem occurs... (Fill in here)
Every time I launch the program.
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. starting the program
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.60 (latest as of this post)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
It doesn't work in a previous version either.
### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

Extra Info: I run a Windows 10 64bit PC. I'm using a Logitech G810 Keyboard.

**Comment by antonpup** [comment]
Umm... extract the zip. lol

Or use web installer.

**Comment by Sharpie3421** [comment]
It didn't work. The program just shows up in Task Manager then closes after a short period of time.
https://gyazo.com/5589950498c7aa32876eb041eedc81e7

**Comment by antonpup** [comment]
Post the log please.

**Comment by Sharpie3421** [comment]
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\Windows\system32
Processor Count: 6
User DomainName: DESKTOP-38V730U
User Name: User
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 3/7/2017 6:28:19 PM: Aurora is already running.
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\Windows\system32
Processor Count: 6
User DomainName: DESKTOP-38V730U
User Name: User
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

3/7/2017 6:28:51 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 57
3/7/2017 6:28:51 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 71
[INFO] 3/7/2017 6:28:51 PM: Loading Configuration
[INFO] 3/7/2017 6:28:52 PM: Loading Device Manager
[INFO] 3/7/2017 6:28:52 PM: Device, Logitech, was initialized
[ERROR] 3/7/2017 6:28:52 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 3/7/2017 6:28:52 PM: Device, Corsair, was not initialized
[INFO] 3/7/2017 6:28:52 PM: No Chroma SDK available
[ERROR] 3/7/2017 6:28:52 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 3/7/2017 6:28:52 PM: Device, Razer, was not initialized
[INFO] 3/7/2017 6:28:52 PM: Could not connect to Clevo WMI Interface
[ERROR] 3/7/2017 6:28:52 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 3/7/2017 6:28:52 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 3/7/2017 6:28:53 PM: Cooler Master device control could not be initialized
[INFO] 3/7/2017 6:28:53 PM: Device, Cooler Master, was not initialized
[INFO] 3/7/2017 6:28:53 PM: Device, AtmoOrb, was initialized
[INFO] 3/7/2017 6:28:53 PM: Retrying Device Initialization
[ERROR] 3/7/2017 6:28:53 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 3/7/2017 6:28:53 PM: Loading KB Layouts
[INFO] 3/7/2017 6:28:53 PM: Device, Corsair, was not initialized
[INFO] 3/7/2017 6:28:53 PM: No Chroma SDK available
[ERROR] 3/7/2017 6:28:53 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 3/7/2017 6:28:53 PM: Device, Razer, was not initialized
[INFO] 3/7/2017 6:28:53 PM: Could not connect to Clevo WMI Interface
[ERROR] 3/7/2017 6:28:53 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 3/7/2017 6:28:53 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 3/7/2017 6:28:53 PM: Cooler Master device control could not be initialized
[INFO] 3/7/2017 6:28:53 PM: Device, Cooler Master, was not initialized
[INFO] Baseline X = 0
[INFO] Baseline Y = 0
[INFO] 3/7/2017 6:28:53 PM: Input Hooking
[INFO] 3/7/2017 6:28:53 PM: Starting GameEventHandler
[INFO] 3/7/2017 6:28:53 PM: Starting GameStateListener
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\Windows\system32
Processor Count: 6
User DomainName: DESKTOP-38V730U
User Name: User
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

3/7/2017 6:31:41 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 57
3/7/2017 6:31:42 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 71
[INFO] 3/7/2017 6:31:42 PM: Loading Configuration
[INFO] 3/7/2017 6:31:43 PM: Loading Device Manager
[INFO] 3/7/2017 6:31:43 PM: Device, Logitech, was initialized
[ERROR] 3/7/2017 6:31:43 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 3/7/2017 6:31:43 PM: Device, Corsair, was not initialized
[INFO] 3/7/2017 6:31:43 PM: No Chroma SDK available
[ERROR] 3/7/2017 6:31:43 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 3/7/2017 6:31:43 PM: Device, Razer, was not initialized
[INFO] 3/7/2017 6:31:43 PM: Could not connect to Clevo WMI Interface
[ERROR] 3/7/2017 6:31:43 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 3/7/2017 6:31:43 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 3/7/2017 6:31:43 PM: Cooler Master device control could not be initialized
[INFO] 3/7/2017 6:31:43 PM: Device, Cooler Master, was not initialized
[INFO] 3/7/2017 6:31:43 PM: Device, AtmoOrb, was initialized
[INFO] 3/7/2017 6:31:43 PM: Retrying Device Initialization
[ERROR] 3/7/2017 6:31:43 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 3/7/2017 6:31:43 PM: Device, Corsair, was not initialized
[INFO] 3/7/2017 6:31:43 PM: Loading KB Layouts
[INFO] 3/7/2017 6:31:43 PM: No Chroma SDK available
[ERROR] 3/7/2017 6:31:43 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 3/7/2017 6:31:43 PM: Device, Razer, was not initialized
[INFO] 3/7/2017 6:31:43 PM: Could not connect to Clevo WMI Interface
[ERROR] 3/7/2017 6:31:43 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 3/7/2017 6:31:43 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 3/7/2017 6:31:43 PM: Cooler Master device control could not be initialized
[INFO] 3/7/2017 6:31:43 PM: Device, Cooler Master, was not initialized
[INFO] Baseline X = 0
[INFO] Baseline Y = 0
[INFO] 3/7/2017 6:31:43 PM: Input Hooking
[INFO] 3/7/2017 6:31:43 PM: Starting GameEventHandler
[INFO] 3/7/2017 6:31:43 PM: Starting GameStateListener
[INFO] 3/7/2017 6:31:58 PM: Retrying Device Initialization
[ERROR] 3/7/2017 6:31:58 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 3/7/2017 6:31:58 PM: Device, Corsair, was not initialized
[INFO] 3/7/2017 6:31:58 PM: No Chroma SDK available
[ERROR] 3/7/2017 6:31:58 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 3/7/2017 6:31:59 PM: Device, Razer, was not initialized
[INFO] 3/7/2017 6:31:59 PM: Could not connect to Clevo WMI Interface
[ERROR] 3/7/2017 6:31:59 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 3/7/2017 6:31:59 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 3/7/2017 6:31:59 PM: Cooler Master device control could not be initialized
[INFO] 3/7/2017 6:31:59 PM: Device, Cooler Master, was not initialized
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\Windows\system32
Processor Count: 6
User DomainName: DESKTOP-38V730U
User Name: User
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

3/7/2017 6:40:07 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 57
3/7/2017 6:40:07 PM: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 71
[INFO] 3/7/2017 6:40:07 PM: Loading Configuration
[INFO] 3/7/2017 6:40:08 PM: Loading Device Manager
[INFO] 3/7/2017 6:40:08 PM: Device, Logitech, was initialized
[ERROR] 3/7/2017 6:40:08 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 3/7/2017 6:40:08 PM: Device, Corsair, was not initialized
[INFO] 3/7/2017 6:40:08 PM: No Chroma SDK available
[ERROR] 3/7/2017 6:40:08 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 3/7/2017 6:40:08 PM: Device, Razer, was not initialized
[INFO] 3/7/2017 6:40:08 PM: Could not connect to Clevo WMI Interface
[ERROR] 3/7/2017 6:40:08 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 3/7/2017 6:40:08 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 3/7/2017 6:40:08 PM: Cooler Master device control could not be initialized
[INFO] 3/7/2017 6:40:08 PM: Device, Cooler Master, was not initialized
[INFO] 3/7/2017 6:40:08 PM: Device, AtmoOrb, was initialized
[INFO] 3/7/2017 6:40:08 PM: Retrying Device Initialization
[ERROR] 3/7/2017 6:40:08 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 3/7/2017 6:40:08 PM: Loading KB Layouts
[INFO] 3/7/2017 6:40:08 PM: Device, Corsair, was not initialized
[INFO] 3/7/2017 6:40:08 PM: No Chroma SDK available
[ERROR] 3/7/2017 6:40:08 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 3/7/2017 6:40:08 PM: Device, Razer, was not initialized
[INFO] 3/7/2017 6:40:08 PM: Could not connect to Clevo WMI Interface
[ERROR] 3/7/2017 6:40:08 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 3/7/2017 6:40:08 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 3/7/2017 6:40:08 PM: Cooler Master device control could not be initialized
[INFO] 3/7/2017 6:40:08 PM: Device, Cooler Master, was not initialized
[INFO] Baseline X = 0
[INFO] Baseline Y = 0
[INFO] 3/7/2017 6:40:09 PM: Input Hooking
[INFO] 3/7/2017 6:40:09 PM: Starting GameEventHandler
[INFO] 3/7/2017 6:40:09 PM: Starting GameStateListener
[INFO] 3/7/2017 6:40:46 PM: Retrying Device Initialization
[ERROR] 3/7/2017 6:40:46 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 3/7/2017 6:40:46 PM: Device, Corsair, was not initialized
[INFO] 3/7/2017 6:40:46 PM: No Chroma SDK available
[ERROR] 3/7/2017 6:40:46 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 3/7/2017 6:40:46 PM: Device, Razer, was not initialized
[INFO] 3/7/2017 6:40:46 PM: Could not connect to Clevo WMI Interface
[ERROR] 3/7/2017 6:40:46 PM: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 3/7/2017 6:40:46 PM: Device, Clevo Keyboard, was not initialized
[ERROR] 3/7/2017 6:40:46 PM: Cooler Master device control could not be initialized
[INFO] 3/7/2017 6:40:46 PM: Device, Cooler Master, was not initialized

**Comment by Sharpie3421** [comment]
please help?

**Comment by Sharpie3421** [comment]
hey so now its just sticking around in Task Manager... but not opening on my screen

**Comment by Sharpie3421** [comment]
nevermind, it's still closing after a little while.

**Comment by Sharpie3421** [comment]
help me please.

**Comment by Blizzardfall** [comment]
Have you tried in safe mode or without any software running on background?
In my case, I couldn't launch Aurora if Rivatuner Statistics Server(a software that comes with MSI Afterburner) is running.

**Comment by simon-wh** [comment]
Are there any updates on this?

**Comment by simon-wh** [comment]
Please refer to #605 relating to this issue.
