### ISSUE TITLE
Fatal Crash Razer Injection (Chroma App)

### ISSUE THREAD

**Issue by IrealiTY** [antonpup/Aurora#97]
Tried to inject (through Overwatch Injector) the Razer SDK thing to this app:
https://insider.razerzone.com/index.php?threads/app-release-razer-ambilight.9997/

Direct download:
http://esdev.de/RazerAmbilight/Updater/Installer/RazerAmbilightInstaller.exe

My process was:

- install the app
- in Aurora click "Patch Overwatch"
- search for Ambilight Folder -> click ok
- crash

```
---------------------------
Aurora has stopped working
---------------------------
Aurora fatally crashed. Please report the follow to author: 

System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Razer Ambilight\RzChromaSDK.dll' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)

   at System.IO.FileStream..ctor(String path, FileMode mode)

   at Aurora.Profiles.Overwatch.Control_Overwatch.patch_button_Click(Object sender, RoutedEventArgs e) in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Overwatch\Control_Overwatch.xaml.cs:line 41

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.Controls.Primitives.ButtonBase.OnClick()

   at System.Windows.Controls.Button.OnClick()

   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)

   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at Aurora.Program.Main(String[] args) in d:\Repositories\Git\Aurora\Project-Aurora\Program.cs:line 219
```

Obviously this has no real priority as its a third party app but I thought the crash might influence other issues.

**Comment by antonpup** [comment]
Run Aurora as admin when you want to patch. It's a problem with permissions.

**Comment by IrealiTY** [comment]
Ok patching worked but app crashes - maybe it's just to a weird of a hook up.
The debugger throws this error
```
System.ArgumentOutOfRangeException was unhandled
Message: An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Additional information: Index was out of range. Must be non-negative and less than the size of the collection.
```

**Comment by antonpup** [comment]
What did you do to cause that crash? Can you post the full log?

**Comment by IrealiTY** [comment]
My bad I should have mentioned that the Chroma App crashes not Aurora - I guess it's out of your control to fix that? (dont have a full log of the app crash as Visual Studio Debugger gave me that error message after the chroma app crash)

**Comment by antonpup** [comment]
Alright, I'll test it.

**Comment by antonpup** [comment]
It seems to be working for me. Have you tried other Chroma Apps? Are they working for you?
